server:
  port: 8081


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    username: root
    password: 888888
    url: jdbc:mysql://localhost:3307/shangpinhui?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 10
      initial-size: 3
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher